### ISSUE TITLE
Question about metrics min/max

### ISSUE THREAD

**Issue by PhilippeR** [cd-athena/VCA#68]
Hello,
What are the range (min/max) of those metrics ? 

- E Spatial complexity of the frame
- h Temporal complexity of the frame
- epsilon Gradient of the temporal complexity of the frame
- L Brightness of the frame

Thank you.

**Comment by vigneshvijay94** [comment]
L: [0,255]
E: [0,511]
h: [0,511]
Epsilon is the gradient of h; hence, its value range is [0, 1023].

**Comment by VD-NVencC** [comment]
1440p60 clip with an E range greater than 255, what might that mean?
![rstudio](https://user-images.githubusercontent.com/71042674/223227789-a534be58-ae15-4f62-b0ae-a94cf5bf8aac.png)

**Comment by vigneshvijay94** [comment]
Could you please share the video you tested on so that we can reproduce this?

**Comment by VD-NVencC** [comment]
[21frames](https://drive.google.com/file/d/16GmDrJMIfr08xVvcboC7Pf1jjyDRs_dk/view?usp=share_link) were extracted and appear to score exactly as the original recording.
![shell](https://user-images.githubusercontent.com/71042674/223595723-d553c2c5-7582-4f2b-aad0-39807c07ce6c.png)

**Comment by VD-NVencC** [comment]
Didn't realize version 2 was released, compiled v2.0 and ran the test in that environment
![two_point_oh_no](https://user-images.githubusercontent.com/71042674/224526424-c145e908-25f8-47c1-8115-8e261b1ea27b.png)
E, and h moving up compared to 1.5

**Comment by vigneshvijay94** [comment]
For natural video scenes, we don't see E going over 255 (the same can be said about the h feature as well). We didn't add a clipper function or normalization function for the feature values because the interpretation of the results is different for different applications. It is up to the calling application to clip the values above a certain threshold or set a normalization of the feature values if needed.
Regarding v2.0 output, the default CLI uses low-pass DCT optimization. So, the 1440p analysis is similar to the 720p analysis, a fast approximation of the features. Hence, the values are expected to change compared to the normal DCT function. Please use --no-lowpass in the CLI to disable low-pass DCT optimization if needed.
